Combine coverage data with Google Action
cjolowicz/cookiecutter-hypermodern-python pull request #568
Opened 2020-09-27 21:29 UTC by oncleben31

- In `tests` nox session, `coverage` session is automatically called only in interactive mode.
- In `tests` GA workflow, coverage data are saved as artefact for each entry in the matrix.
- In `tests` GA workflow, a `coverage`job is added to download from artefacts all coverage data, combine them and upload the report on codecov.
- Documentation update.

fix #468

2020-09-27 21:30 UTC, oncleben31 commented
@cjolowicz do you have advise for the best way to test my modifications before merging?

2020-10-02 21:27 UTC, oncleben31 commented
I have test in the repo: https://github.com/oncleben31/cookiecutter-hypermodern-python-instance
coverage part is working well.

It was a good exercise to use cookiecutter, pipx, and cupper.

2020-10-08 11:03 UTC, cjolowicz requested changes
Many thanks for your work, perfect! I left some inline comments with suggestions. (These are very minor points. I can also address them in the merge, if you don't get around to it yourself.) 

And sorry for not being able to help out with testing earlier. I see you figured out a solution. That's exactly how I do it as well.

2020-10-08 16:25 UTC, oncleben31 commented on {{cookiecutter.project_name}}/.github/workflows/tests.yml
> +      - name: "Download coverage data"
Done.

2020-10-08 16:43 UTC, oncleben31 commented on docs/guide.rst
Done

2020-10-08 16:45 UTC, oncleben31 commented on {{cookiecutter.project_name}}/.github/workflows/tests.yml
> +          path: {{ "${{ github.workspace }}/.coverage.*" }}
You are right all files have a different name.

2020-10-08 17:00 UTC, oncleben31 commented
Thank you for your detailed feedbacks. They are all taken into account.

2020-10-08 22:07 UTC, cjolowicz approved these changes
Thanks!

Here's a passing and a failing test (with and without your changes, respectively):

- https://github.com/cjolowicz/cookiecutter-hypermodern-python-instance/pull/323
- https://github.com/cjolowicz/cookiecutter-hypermodern-python-instance/pull/324

2020-10-08 22:07 UTC, merged