Add 'package' key in pyproject.toml when necessary
cjolowicz/cookiecutter-hypermodern-python pull request #631
Opened 2020-10-20 23:39 UTC by oncleben31

if the package name and project name are not similar (more than `-` replaced by `_`), a `package` key will be added in `pyproject.toml` file.

Example: 
```toml
packages = [
    { include = "package_name", from = "src" },
]
```

fix: #546

2020-10-20 23:43 UTC, oncleben31 commented
I didn't see any part in documentation that should be update according to this modification of `pyproject.toml`

2020-10-23 12:02 UTC, oncleben31 commented
Failure of tests-3.9 with windows seems not related to my modifications.

2020-11-03 11:35 UTC, cjolowicz requested changes
Awesome, thank you for the contribution! There is an issue related to whitespace handling in Jinja, otherwise looks perfect to me. See the inline comment.

2020-11-03 11:35 UTC, cjolowicz commented on {{cookiecutter.project_name}}/pyproject.toml
> +{%- if cookiecutter.package_name != cookiecutter.project_name.replace('-', '_') -%}
```suggestion
{% if cookiecutter.package_name != cookiecutter.project_name.replace('-', '_') -%}
```

With `{%-` the `documentation` and `packages` keys run into each other.

See  https://jinja.palletsprojects.com/en/2.11.x/templates/#whitespace-control

2020-11-04 09:05 UTC, oncleben31 commented
White space handling corrected. With this version we have a line break between `documentation` and `classifiers` keys when no `packages` key is needed. Is it OK for you ?

2020-11-06 09:22 UTC, cjolowicz commented on {{cookiecutter.project_name}}/pyproject.toml
> +{%- endif %}
> With this version we have a line break between documentation and classifiers keys when no packages key is needed.

Good catch! So the minus in the `endif` should move to the closing tag.

```suggestion
{% endif -%}
```

2020-11-06 10:00 UTC, merged

2020-11-06 10:01 UTC, cjolowicz commented
Woot :tada:

2020-11-06 10:02 UTC, oncleben31 commented
Do you think we should add a test case in CI ?

2020-11-06 10:09 UTC, cjolowicz commented
Yes, but I would not add this to the CI workflow. This should be in a test suite run by pytest, see #616. Unfortunately, we don't have this infrastructure yet. But it's overdue, so if you want to start work on that, that's more than welcome. It's a bunch of work, though.